name: Build/release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest] #macos-latest, ubuntu-latest,

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Vue cli
        run:
          npm install @vue/cli-service-global @vue/cli --save-dev

      - name: 'Build Leaflet'
        working-directory: '.'
        run: |
          npm install
          npx vue-cli-service electron:build